### ISSUE TITLE
For arty-100-nic project dump.sh socket.timeout error

### ISSUE THREAD

**Issue by zaidtahirbutt** [rprinz08/hBPF#2]
I am trying to run the arty-100t-nic project. 

_Run server-start.sh to start the wishbone bridge.
_Run dump.sh which waits til a network packet is completely received and then creates a *.vcd capture file on the host__
When I run dump.sh, it just times out and does not write a vcd capture file.

Can you please help me with that? 

error is below:
  File "/home/zaidtahir/projects/hbpf_2/litex/litex/tools/remote/etherbone.py", line 370, in receive_packet

    chunk = socket.recv(header_length - len(packet))  #original

socket.timeout: timed out

**Comment by rprinz08** [comment]
This looks like a misconfiguration with your serial Arty connection.

**Things to check first:**

* check `source/fpga/hw/arty-a7-100-net/debug/.config` and ensure that `TARGET_PORT` is set to the correct serial
   device your Arty is connected to.

**Next perform the following:**

* open 3 console windows (A,B and C)
* on console A load the Arty with the bitstream from the repo by running `source/fpga/hw/arty-a7-100-net/load.py`
* on console A run `source/fpga/hw/arty-a7-100-net/debug/server_start.sh -f`
   which starts the bridge server in foreground mode showing possible errors.
   When everything is OK this would show something like:
   `[CommUART] port: /dev/xyz / baudrate: 115200 / tcp port: 1234`
   Possible errors show up here too.
* on console B run `dump.sh`. This lists the signal it is listening for and
   pauses until the configured trigger `Falling edge: __main___ethmac_source_ready`
   occurs.
* on console A you should see something like `Connected with 127.0.0.1:46232`
   which shows that the `dump.sh` script has connected to the bridge server
* on console C send a packet to the Arty e.g. `ping -c1 10.0.10.50`
* as soon as the packet is seen by the Arty (blue LED flashes) the paused
   `dump.sh` on console B resumes with a programs bar showing how much data
   it has already downloaded. At 100% you should have a `dump.vcd` in the debug
   directory.
* Viewing the `dump.vcd` is performed using `gtkwave dump.vcd dump.gtkw`. Looking
   at the `...payload_data` fields you should see, byte by byte, the received
   packet.

**Comment by zaidtahirbutt** [comment]
Thanks a lot! I'll try these and will close the issue if this works.

**Comment by zaidtahirbutt** [comment]
Hi I tried all the steps but I get a socket receive timeout error as soon as I send the ping from the ethernet.
Btw in order to send ping from the lan cable I used command "ping  -I eno1 10.0.10.50" (eno1 is name of my ethernet adapter).

**Comment by rprinz08** [comment]
I'm sorry, but I think it has to do with your system setup. Tried on multiple boards and works as expected. What is shown on console A? Bridge and dump tool communicate locally using TCP where the bridge server listens on port 1234 for commands
from clients like the `dump.sh` utility. On Linux using `sudo netstat -uanp` (assuming you have the net-tool package installed) you should see something like `tcp        0      0 127.0.0.1:1234          0.0.0.0:*               LISTEN      7674/python3` when the server is running. Might also be an option to try disabling any firewalls and see how that works. Anyway, that's pretty sure a problem of your local PC setup then a problem of hBPF.
