### ISSUE TITLE
Division by zero logic is incorrect

### ISSUE THREAD

**Issue by dthaler** [rprinz08/hBPF#4]
Per https://github.com/ebpffoundation/ebpf-docs/blob/pdf/instruction-set.pdf based on Linux Plumbers Conference discussion and bpf list discussion requires that
x / 0 => 0
x % 0 => x

Currently hBPF does not do this.  See
* https://github.com/rprinz08/hBPF/blob/main/source/emulator/ebpf/vm_alu.py#L131
* https://github.com/rprinz08/hBPF/blob/main/source/emulator/ebpf/vm_alu.py#L242
* https://github.com/rprinz08/hBPF/blob/main/source/fpga/math/divide.py#L88
* https://github.com/rprinz08/hBPF/blob/main/source/fpga/math/divide.py#L95
etc.

**Comment by rprinz08** [comment]
Thanks, fixed with commit 3742d93b79a597faefe58aa521ed86410d4ad6ba
