### ISSUE TITLE
How to use hBPF call handlers in C code? 

### ISSUE THREAD

**Issue by zaidtahirbutt** [rprinz08/hBPF#7]
Hi, 

Following is an example from your readme regarding using call handler for hBPF.

How can I use/compile such a call handler for hBPF in C code?

```
# Set input registers
mov r1, 10
mov r2, 3
# Call function 1 (subtract)
call 1
# Result is available in R0 after call op-code returns
```

**Comment by zaidtahirbutt** [comment]
Also all of the examples in C folder inside the development folder like: https://github.com/rprinz08/hBPF/blob/main/development/C/prime.c , have c files with just functions in it (there is no main function). The assembly code makes sense. Is there a working example of the c code being used for the hBPF? 

For example in prime.c as shown below, what is args in the function w.r.t this c code running on hBPF?

```
#include <stdbool.h>

bool function(unsigned long int arg) {

    for(unsigned long int i = 2; i < arg; i++)
        if (arg % i == 0)
            return false;

    return true;
}
```

**Comment by rprinz08** [comment]
Hi,

just updated the repo to include a sample for this: https://github.com/rprinz08/hBPF/blob/main/development/C/call.c 
Hope that helps

**Comment by zaidtahirbutt** [comment]
@rprinz08 thanks for uploading that. I found the rest of the answer in the readme of this file. Also thanks for updating the bash scripts of the c files.
